### ISSUE TITLE
Update to "Active" version of NodeJS

### ISSUE THREAD

**Issue by mountainash** [dockette/vercel#1]
The current build is running NodeJS v.14.5.0 which is no longer an "Active" release - https://nodejs.org/en/about/releases/

Could a new build be triggered to pull a newer version of Node JS?

**Comment by f3l1x** [comment]
I will, thanks for report.

**Comment by f3l1x** [comment]
Solved https://hub.docker.com/r/dockette/vercel

**Comment by mountainash** [comment]
Awesome - thank you very much for the quick resolution on this. 🔥
